try github action

diff --git a/.github/workflows/push-release.yml b/.github/workflows/push-release.yml
--- a/.github/workflows/push-release.yml
+++ b/.github/workflows/push-release.yml
@@ -11,164 +11,165 @@ env:
   IMAGE: ${{ github.repository_owner }}/rancher
   IMAGE_AGENT: ${{ github.repository_owner }}/rancher-agent
   IMAGE_INSTALLER: ${{ github.repository_owner }}/system-agent-installer-rancher
-  env_var: ${{ vars.ENV_CONTEXT_VAR }}
 jobs:
-  build-server:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        os: [linux]
-        arch: [amd64]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      # Cleaning the runner is important to free enough space to build rancher, otherwise the build will fail
-      - name: Clean runner
-        run: |
-          # removes dotnet
-          sudo rm -rf /usr/share/dotnet
-          # removes haskell
-          sudo rm -rf /opt/ghc
-          # removes android sdk
-          sudo rm -rf /usr/local/lib/android
-      - name: Setup Environment Variables
-        uses: ./.github/actions/setup-tag-env
-      - id: env 
-        name: Setup Dependencies Env Variables
-        uses: ./.github/actions/setup-build-env
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.IMAGE }}
-          flavor: |
-            latest=false
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Create k3s images file
-        uses: ./.github/actions/k3s-images
-        with:
-          k3s_version: ${{ steps.env.outputs.CATTLE_K3S_VERSION }}
-      - name: Download data.json
-        run: curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ steps.env.outputs.CATTLE_KDM_BRANCH }}/data.json > ./data.json
-      - name: Build and export server
-        id: build
-        uses: docker/build-push-action@v5
-        with:
-          push: false
-          build-args: |
-            "VERSION=${{ env.TAG }}"
-            "COMMIT=${{ env.COMMIT }}"
-            "RKE_VERSION=${{ steps.env.outputs.RKE_VERSION }}"
-            "ARCH=${{ matrix.arch }}"
-            "CATTLE_RANCHER_WEBHOOK_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}"
-            "CATTLE_CSP_ADAPTER_MIN_VERSION=${{ steps.env.outputs.CATTLE_CSP_ADAPTER_MIN_VERSION }}"
-            "CATTLE_FLEET_VERSION=${{ steps.env.outputs.CATTLE_FLEET_VERSION }}"
-          tags: ${{ env.IMAGE }}:${{ env.TAG }}-${{ matrix.arch }}
-          context: .
-          platforms: "${{ matrix.os }}/${{ matrix.arch }}"
-          file: ./package/Dockerfile
-          labels: "${{ steps.meta.outputs.labels }}"
-          outputs: type=docker,dest=/tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
-      - name: Upload image
-        uses: actions/upload-artifact@v4
-        with:
-          name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
-          path: /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
-          if-no-files-found: error
-          retention-days: 1
-          overwrite: false
-  build-agent:
-    needs: [build-server]
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        os: [linux]
-        arch: [amd64]
-    services:
-      registry:
-        image: registry:2
-        ports:
-          - 5000:5000
-    env:
-      REGISTRY: "127.0.0.1:5000"
-    steps:
-      # Cleaning the runner is important to free enough space to build rancher, otherwise the build will fail
-      - name: Clean runner
-        run: |
-          # removes dotnet
-          sudo rm -rf /usr/share/dotnet
-          # removes haskell
-          sudo rm -rf /opt/ghc
-          # removes android sdk
-          sudo rm -rf /usr/local/lib/android
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Setup Environment Variables
-        run: |
-          echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
-          source scripts/export-config
-          echo "CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION" >> "$GITHUB_ENV"
-      - name: Setup TAG Variables
-        uses: ./.github/actions/setup-tag-env
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.IMAGE }}
-          flavor: |
-            latest=false
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          driver-opts: network=host
-      - name: Download rancher image
-        uses: actions/download-artifact@v4
-        with:
-          name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
-          path: /tmp
-      - name: Load image
-        run: |
-          image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
-          if [ -z "$image_id" ]; then
-            echo "Error: Failed to load image from tarball!"
-            exit 1
-          fi
-          docker tag "$image_id" ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
-          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
-      - name: Build agent
-        id: build
-        uses: docker/build-push-action@v5
-        with:
-          push: false
-          build-args: |
-            "VERSION=${{ env.TAG }}"
-            "ARCH=${{ matrix.arch }}"
-            "RANCHER_TAG=${{ env.TAG }}"
-            "RANCHER_REPO=${{ env.REPOSITORY_OWNER }}"
-            "REGISTRY=${{ env.REGISTRY }}"
-            "CATTLE_RANCHER_WEBHOOK_VERSION=${{ env.CATTLE_RANCHER_WEBHOOK_VERSION }}"
-          tags: ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-${{ matrix.arch }}
-          context: .
-          platforms: "${{ matrix.os }}/${{ matrix.arch }}"
-          file: ./package/Dockerfile.agent
-          labels: "${{ steps.meta.outputs.labels }}"
-          outputs: type=docker,dest=/tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
-      - name: Upload image
-        uses: actions/upload-artifact@v4
-        with:
-          name: "rancher-agent-${{ matrix.os }}-${{ matrix.arch }}"
-          path: /tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
-          if-no-files-found: error
-          retention-days: 1
-          overwrite: false
+  # build-server:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       os: [linux]
+  #       arch: [amd64]
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     # Cleaning the runner is important to free enough space to build rancher, otherwise the build will fail
+  #     - name: Clean runner
+  #       run: |
+  #         # removes dotnet
+  #         sudo rm -rf /usr/share/dotnet
+  #         # removes haskell
+  #         sudo rm -rf /opt/ghc
+  #         # removes android sdk
+  #         sudo rm -rf /usr/local/lib/android
+  #     - name: Setup Environment Variables
+  #       uses: ./.github/actions/setup-tag-env
+  #     - id: env 
+  #       name: Setup Dependencies Env Variables
+  #       uses: ./.github/actions/setup-build-env
+  #     - name: Docker meta
+  #       id: meta
+  #       uses: docker/metadata-action@v5
+  #       with:
+  #         images: ${{ env.IMAGE }}
+  #         flavor: |
+  #           latest=false
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #     - name: Create k3s images file
+  #       uses: ./.github/actions/k3s-images
+  #       with:
+  #         k3s_version: ${{ steps.env.outputs.CATTLE_K3S_VERSION }}
+  #     - name: Download data.json
+  #       run: curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ steps.env.outputs.CATTLE_KDM_BRANCH }}/data.json > ./data.json
+  #     - name: Build and export server
+  #       id: build
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         push: false
+  #         build-args: |
+  #           "VERSION=${{ env.TAG }}"
+  #           "COMMIT=${{ env.COMMIT }}"
+  #           "RKE_VERSION=${{ steps.env.outputs.RKE_VERSION }}"
+  #           "ARCH=${{ matrix.arch }}"
+  #           "CATTLE_RANCHER_WEBHOOK_VERSION=${{ steps.env.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}"
+  #           "CATTLE_CSP_ADAPTER_MIN_VERSION=${{ steps.env.outputs.CATTLE_CSP_ADAPTER_MIN_VERSION }}"
+  #           "CATTLE_FLEET_VERSION=${{ steps.env.outputs.CATTLE_FLEET_VERSION }}"
+  #         tags: ${{ env.IMAGE }}:${{ env.TAG }}-${{ matrix.arch }}
+  #         context: .
+  #         platforms: "${{ matrix.os }}/${{ matrix.arch }}"
+  #         file: ./package/Dockerfile
+  #         labels: "${{ steps.meta.outputs.labels }}"
+  #         outputs: type=docker,dest=/tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
+  #     - name: Upload image
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
+  #         path: /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
+  #         if-no-files-found: error
+  #         retention-days: 1
+  #         overwrite: false
+  # build-agent:
+  #   needs: [build-server]
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       os: [linux]
+  #       arch: [amd64]
+  #   services:
+  #     registry:
+  #       image: registry:2
+  #       ports:
+  #         - 5000:5000
+  #   env:
+  #     REGISTRY: "127.0.0.1:5000"
+  #   steps:
+  #     # Cleaning the runner is important to free enough space to build rancher, otherwise the build will fail
+  #     - name: Clean runner
+  #       run: |
+  #         # removes dotnet
+  #         sudo rm -rf /usr/share/dotnet
+  #         # removes haskell
+  #         sudo rm -rf /opt/ghc
+  #         # removes android sdk
+      #     sudo rm -rf /usr/local/lib/android
+      # - name: Checkout code
+      #   uses: actions/checkout@v4
+      # - name: Setup Environment Variables
+      #   run: |
+      #     echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
+      #     source scripts/export-config
+      #     echo "CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION" >> "$GITHUB_ENV"
+      # - name: Setup TAG Variables
+      #   uses: ./.github/actions/setup-tag-env
+      # - name: Docker meta
+      #   id: meta
+      #   uses: docker/metadata-action@v5
+      #   with:
+      #     images: ${{ env.IMAGE }}
+      #     flavor: |
+      #       latest=false
+      # - name: Set up QEMU
+      #   uses: docker/setup-qemu-action@v3
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v3
+      #   with:
+      #     driver-opts: network=host
+      # - name: Download rancher image
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
+      #     path: /tmp
+      # - name: Load image
+      #   run: |
+      #     image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
+      #     if [ -z "$image_id" ]; then
+      #       echo "Error: Failed to load image from tarball!"
+      #       exit 1
+      #     fi
+      #     docker tag "$image_id" ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
+      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
+      # - name: Build agent
+      #   id: build
+      #   uses: docker/build-push-action@v5
+      #   with:
+      #     push: false
+      #     build-args: |
+      #       "VERSION=${{ env.TAG }}"
+      #       "ARCH=${{ matrix.arch }}"
+      #       "RANCHER_TAG=${{ env.TAG }}"
+      #       "RANCHER_REPO=${{ env.REPOSITORY_OWNER }}"
+      #       "REGISTRY=${{ env.REGISTRY }}"
+      #       "CATTLE_RANCHER_WEBHOOK_VERSION=${{ env.CATTLE_RANCHER_WEBHOOK_VERSION }}"
+      #     tags: ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-${{ matrix.arch }}
+      #     context: .
+      #     platforms: "${{ matrix.os }}/${{ matrix.arch }}"
+      #     file: ./package/Dockerfile.agent
+      #     labels: "${{ steps.meta.outputs.labels }}"
+      #     outputs: type=docker,dest=/tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
+      # - name: Upload image
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: "rancher-agent-${{ matrix.os }}-${{ matrix.arch }}"
+      #     path: /tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
+      #     if-no-files-found: error
+      #     retention-days: 1
+      #     overwrite: false
   push-images:
-    needs: [build-agent]
+    # needs: [build-agent]
     runs-on: ubuntu-latest
+    environment:
+      name: dev
     permissions:
       contents: read
       id-token: write
